# Generated by Django 3.2.15 on 2022-10-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_transations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transation_date', models.DateField()),
                ('user_id', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('narration', models.CharField(max_length=200)),
                ('receipt_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='purchase_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sales_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('grnd_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='./myapp/download.jpg', upload_to='./myapp/images'),
        ),
    ]
