# Generated by Django 3.2.15 on 2022-11-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20221105_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=50)),
            ],
        ),
    ]
