# Generated by Django 4.2 on 2023-05-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_cart_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_transations',
        ),
        migrations.DeleteModel(
            name='item_category',
        ),
        migrations.DeleteModel(
            name='plan_settings',
        ),
        migrations.DeleteModel(
            name='purchase_details',
        ),
        migrations.DeleteModel(
            name='sales_bill',
        ),
    ]
