# Generated by Django 4.2 on 2023-05-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quant',
        ),
    ]
