# Generated by Django 4.2 on 2023-05-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_product_quant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
