# Generated by Django 4.2 on 2023-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tm',
        ),
        migrations.AddField(
            model_name='purchase',
            name='size',
            field=models.CharField(default='', max_length=25),
        ),
    ]
