# Generated by Django 4.2 on 2023-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_purchase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mobile',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
