# Generated by Django 3.2.15 on 2022-10-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('image', models.FileField(default='', upload_to='myapp/images')),
            ],
        ),
    ]
