# Generated by Django 4.2 on 2023-05-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_purchase_dt_remove_purchase_tm_purchase_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
