# Generated by Django 4.2 on 2023-05-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_purchase_mobile_purchase_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='shipping_address',
            new_name='address',
        ),
    ]
