# Generated by Django 4.2 on 2023-05-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_shipping_address_purchase_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
